name = "telegram-shop-bot"
main = "src/index.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "shop_db"
database_id = "50bfaf68-f506-4ad6-977f-8d3b56645971"

[[kv_namespaces]]
binding = "KV"
id = "db27339b15544397b43b3d102c4494f4"
