name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # در این خط، متغیرها مستقیماً از سکرتز خوانده شده و به کلودفلر تزریق می‌شوند
          command: deploy --var BOT_TOKEN:${{ secrets.BOT_TOKEN }} --var ADMIN_ID:${{ secrets.ADMIN_ID }} --var CHANNEL_ID:${{ secrets.CHANNEL_ID }} --var CARD_NUMBER:${{ secrets.CARD_NUMBER }}
